#!/usr/bin/env python3
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
replacements={
"about.html":{
"Mais do que produtos: uma experiência feita para facilitar boas escolhas.":"Uma loja feita para receber você com calma.",
"A <span data-config-nome>Saúde Qualimax</span> aproxima variedade, informação e atendimento humano em uma experiência simples de explorar.":"Na <span data-config-nome>Saúde Qualimax</span>, cada escolha começa com escuta, informação clara e tempo para decidir.",
"Em <span data-config-localidade>Serra - ES</span>, reunimos produtos naturais, sabores, aromas e possibilidades em uma experiência feita para quem gosta de descobrir antes de escolher.":"Em <span data-config-localidade>Serra - ES</span>, reunimos produtos naturais, sabores e aromas para quem gosta de olhar com calma, perguntar e escolher sem pressão.",
"Você explora do seu jeito. A plataforma organiza o caminho e nossa equipe entra quando você quiser conversar.":"Você olha no seu tempo. Quando quiser conversar, nossa equipe chega junto.",
"Organizamos o catálogo para transformar variedade em clareza: categorias, filtros, favoritos e recursos de descoberta ajudam você a encontrar opções sem se perder no excesso.":"Organizamos tudo para que a variedade não vire confusão. Você pode passear pelas categorias, guardar o que gostou e comparar apenas quando fizer sentido.",
"Quer sair da tela e continuar a descoberta de perto?":"Que tal continuar essa conversa de perto?"},
"account.html":{"Sua experiência neste dispositivo":"Seu cantinho neste aparelho","Guarde seus dados básicos, reveja produtos salvos e continue de onde parou. Nesta versão, tudo fica somente neste navegador.":"Aqui ficam seus favoritos, sua lista e os produtos vistos recentemente. Tudo é guardado somente neste aparelho, para você voltar com tranquilidade.","Fidelidade demonstrativa":"Um carinho para quem volta","Cupons demonstrativos disponíveis":"Benefícios disponíveis para conhecer"},
"budget-planner.html":{"Escolha sem ultrapassar o teto":"Seu bolso também merece cuidado","Planejador de orçamento":"Monte uma seleção que caiba no seu orçamento","Compare três níveis de seleção usando apenas produtos do catálogo.":"Conte quanto pretende gastar. A gente organiza três caminhos possíveis com produtos do catálogo, e você escolhe sem pressa."},
"campaigns.html":{"Descobertas da estação":"Boas escolhas para este momento","Campanhas e seleções especiais":"Seleções que preparamos com carinho","Campanhas ativas aparecem automaticamente conforme as datas definidas pelo administrador.":"Aqui você encontra combinações e oportunidades disponíveis agora. Confira com calma e leve apenas o que fizer sentido para você.","Kits e combos":"Combinações que ficam bem juntas"},
"compare.html":{"Decisão com clareza":"Coloque lado a lado e escolha com calma","Comparador profissional":"Compare o que realmente importa"},
"contact.html":{"Quer resolver de casa ou prefere passar na loja? Os dois caminhos começam aqui.":"Quer conversar de casa ou fazer uma visita? A gente recebe você dos dois jeitos.","Prepare seu atendimento com nome, lista e forma de recebimento para agilizar a conversa — ou venha conhecer a loja pessoalmente no endereço abaixo.":"Se quiser, deixe seu atendimento encaminhado antes de chamar no WhatsApp. Se preferir vir até a loja, o endereço e os contatos estão logo abaixo.","Antes de pedir ou visitar, confira o que importa.":"Tudo o que você precisa saber antes de falar com a gente.","Horários, entrega e retirada ficam reunidos aqui para você planejar o próximo passo sem adivinhação.":"Reunimos horários, entrega e retirada para você se organizar sem surpresa."},
"discover.html":{"Explore por ocasião":"Comece pelo momento que você está vivendo","Descobrir":"O que combina com o seu dia hoje?","Comece por um momento da rotina, sem precisar saber o nome do produto.":"Talvez você queira um lanche gostoso, uma pausa com chá ou algo prático para a rotina. Escolha um caminho e veja o que aparece."},
"guided-shopping.html":{"MAX em modo guiado":"O Max pergunta, você responde do seu jeito","Compra guiada":"Vamos encontrar um bom caminho juntos?","Responda a três etapas e receba uma seleção dentro dos seus critérios.":"São só três perguntas simples. No final, o Max reúne opções próximas do que você contou — sem decidir por você."},
"journey.html":{"Tudo em um só lugar":"As escolhas que você fez pelo caminho","Minha Jornada":"Seu caminho pela loja","Veja escolhas e lembretes guardados somente neste navegador.":"Reencontre produtos, comparações e lembretes que ficaram guardados neste aparelho. Nada sai daqui sem sua ação."},
"kit-builder.html":{"Seleção personalizada":"Uma combinação com a sua cara","Construtor de kits":"Monte seu kit, do seu jeito"},
"offline.html":{"Você está sem conexão no momento.":"A internet deu uma pausa. Você ainda pode respirar por aqui.","Algumas páginas e produtos que você já visitou podem continuar disponíveis. Recursos que precisam de internet, como WhatsApp e atualização do catálogo, voltarão a funcionar quando a conexão for restabelecida.":"As páginas que você já visitou podem continuar disponíveis. Assim que a conexão voltar, o catálogo se atualiza e o WhatsApp funciona novamente — você não precisa fazer nada."},
"quiz.html":{"Menos procura. Mais opções com a sua cara.":"Algumas perguntas, um caminho mais leve.","Responda algumas perguntas e transforme um catálogo inteiro em uma seleção mais próxima do que você procura.":"Conte um pouco do que você gosta e veja opções mais próximas da sua rotina.","Não existe resposta certa. Suas escolhas servem apenas para aproximar produtos do catálogo das suas preferências; preço e disponibilidade continuam sendo confirmados pela equipe.":"Não existe resposta certa ou errada. O quiz só ajuda a organizar o catálogo; você continua livre para olhar, comparar e mudar de ideia."},
"recipes.html":{"Ideias compráveis":"Ideias gostosas para colocar em prática","Receitas e combinações":"Um pouco de inspiração para a sua cozinha","As sugestões são culinárias e devem respeitar rótulos, alergias e orientações individuais.":"Use estas ideias como ponto de partida e adapte ao seu gosto. Se houver alergias ou restrições, confira sempre o rótulo de cada ingrediente."},
"support.html":{"Pré-atendimento inteligente":"Vamos adiantar só o necessário","Vamos deixar seu atendimento adiantado?":"Quer chegar ao WhatsApp com tudo organizado?","Preencha só o necessário. No final, você revisa tudo e decide se quer abrir a conversa no WhatsApp.":"Conte apenas o que for importante para o pedido. Antes de abrir o WhatsApp, você confere a mensagem inteira e pode mudar o que quiser.","O pagamento é combinado com a equipe. A plataforma não recebe pagamentos.":"O pagamento é acertado diretamente com a equipe. Nenhuma cobrança acontece nesta página."},
"catalog.html":{"47 produtos. Muitos caminhos para encontrar o que combina com você.":"Um catálogo cheio de possibilidades — e liberdade para olhar no seu tempo.","Encontre o que veio buscar — e descubra o que ainda não estava procurando.":"Encontre o que procura. Se aparecer uma boa surpresa pelo caminho, melhor ainda.","Pesquise pelo nome, filtre por categoria ou característica e compare opções sem perder tempo. Se algo chamar sua atenção, salve para decidir depois.":"Você pode buscar pelo nome, passear pelas categorias ou usar os filtros. Gostou de algo? Guarde para rever depois, sem precisar decidir agora."}}
for name,mapping in replacements.items():
 p=root/name;s=p.read_text(encoding="utf-8")
 for old,new in mapping.items():
  if old not in s:print(f"AVISO: texto não encontrado em {name}: {old[:50]}")
  s=s.replace(old,new)
 p.write_text(s,encoding="utf-8")

data_path=root/"data/products.json";data=json.loads(data_path.read_text(encoding="utf-8"))
openers=["Vale conhecer com calma","Uma escolha simples para ter por perto","Daquelas opções que entram na rotina sem cerimônia","Para descobrir no seu tempo","Uma possibilidade prática para o dia a dia","Se chamou sua atenção, chegue mais perto"]
closers=["Confira a apresentação e veja se combina com o que você procura.","Leia os detalhes, compare e escolha somente se fizer sentido para você.","Conheça os detalhes e, se surgir dúvida, converse com a equipe.","Veja o formato, a quantidade e o preço antes de decidir.","Explore as informações e guarde para comparar depois, se quiser.","A equipe pode ajudar a esclarecer composição, disponibilidade e formas de uso indicadas no rótulo."]
ctas=["Quero conhecer melhor","Ver detalhes com calma","Conferir esta opção","Conhecer apresentação e preço","Quero saber mais","Explorar este produto"]
for i,p in enumerate(data.get("produtos",[])):
 name=str(p.get("nome") or "Este produto");presentation=str(p.get("apresentacao") or "a apresentação cadastrada");category=str(p.get("categoria") or "produto natural").replace("-"," ")
 p["descricao"]=f"{name}, na apresentação {presentation}, disponível no catálogo da loja. Consulte rótulo, composição e disponibilidade com a equipe."
 p["copy"]=f"{openers[i%len(openers)]}: {name} é uma opção da categoria {category}, na apresentação {presentation}. {closers[(i*2)%len(closers)]}"
 p["cta"]=ctas[i%len(ctas)]
 p["preco_aproximado"]=False
data_path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
print(f"Copy revisada em {len(replacements)} páginas e {len(data.get('produtos',[]))} produtos")
