#!/usr/bin/env python3
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]

products_path=ROOT/"data/products.json";data=json.loads(products_path.read_text(encoding="utf-8"));products=data["produtos"]
new=[
{"id":48,"nome":"Quinoa em Grãos","categoria":"cereais","imagem":"quinoa-grains.webp","descricao":"Quinoa em grãos para saladas, acompanhamentos e receitas do dia a dia.","beneficios":["Versatilidade culinária","Grãos","Receitas"],"tipo":"grao","vegana":True,"sem_gluten":True,"experiencia_minima":"iniciante","tags":["quinoa","graos","salada","cozinha"],"disponibilidade":"consultar","destaque":True,"copy":"Um grão versátil para variar saladas, acompanhamentos e preparos quentes. Conheça a apresentação e leve uma nova possibilidade para a cozinha.","cta":"Conhecer a quinoa","slug":"quinoa-grains","preco":12.90,"apresentacao":"200 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":200,"unidade_venda":"g","incremento":200},
{"id":49,"nome":"Amaranto em Flocos","categoria":"cereais","imagem":"amaranth-flakes.webp","descricao":"Flocos de amaranto para frutas, iogurtes, vitaminas e receitas.","beneficios":["Praticidade","Cereais","Café da manhã"],"tipo":"flocos","vegana":True,"sem_gluten":True,"experiencia_minima":"iniciante","tags":["amaranto","flocos","cafe da manha","receitas"],"disponibilidade":"consultar","destaque":False,"copy":"Flocos leves e fáceis de combinar com frutas, bebidas e receitas. Uma opção prática para dar variedade ao café da manhã.","cta":"Ver amaranto","slug":"amaranth-flakes","preco":10.90,"apresentacao":"200 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":200,"unidade_venda":"g","incremento":200},
{"id":50,"nome":"Farinha de Amêndoas","categoria":"farinhas","imagem":"almond-flour.webp","descricao":"Farinha de amêndoas para bolos, pães, massas e receitas variadas.","beneficios":["Panificação","Receitas","Oleaginosas"],"tipo":"po","vegana":True,"sem_gluten":True,"experiencia_minima":"intermediario","tags":["farinha","amendoas","bolo","pao","sem gluten"],"disponibilidade":"consultar","destaque":True,"copy":"Uma farinha de sabor delicado para explorar bolos, pães e massas. Compare a apresentação e descubra novas receitas sem complicação.","cta":"Conhecer a farinha","slug":"almond-flour","preco":24.90,"apresentacao":"200 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":200,"unidade_venda":"g","incremento":200},
{"id":51,"nome":"Farinha de Coco","categoria":"farinhas","imagem":"coconut-flour.webp","descricao":"Farinha de coco para receitas doces, massas e preparos culinários.","beneficios":["Sabor de coco","Panificação","Receitas"],"tipo":"po","vegana":True,"sem_gluten":True,"experiencia_minima":"intermediario","tags":["farinha","coco","bolo","receitas","sem gluten"],"disponibilidade":"consultar","destaque":False,"copy":"O aroma do coco em uma farinha para receitas doces e salgadas. Ideal para quem gosta de testar novas texturas na cozinha.","cta":"Ver farinha de coco","slug":"coconut-flour","preco":12.90,"apresentacao":"200 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":200,"unidade_venda":"g","incremento":200},
{"id":52,"nome":"Xilitol","categoria":"alimentos","imagem":"xylitol.webp","descricao":"Xilitol granulado para adoçar bebidas e receitas conforme a preferência.","beneficios":["Uso culinário","Bebidas","Receitas"],"tipo":"granulado","vegana":True,"sem_gluten":True,"experiencia_minima":"intermediario","tags":["xilitol","adocante","bebidas","receitas"],"disponibilidade":"consultar","destaque":True,"copy":"Uma alternativa granulada para adoçar bebidas e preparos. Confira a apresentação e adapte a quantidade ao seu gosto e à receita.","cta":"Conhecer o xilitol","slug":"xylitol","preco":19.90,"apresentacao":"250 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":250,"unidade_venda":"g","incremento":250},
{"id":53,"nome":"Semente de Abóbora sem Casca","categoria":"sementes","imagem":"pumpkin-seeds.webp","descricao":"Sementes de abóbora sem casca para snacks, saladas e receitas.","beneficios":["Crocância","Snack","Receitas"],"tipo":"semente","vegana":True,"sem_gluten":True,"experiencia_minima":"iniciante","tags":["semente","abobora","snack","salada"],"disponibilidade":"consultar","destaque":True,"copy":"Crocante e fácil de usar: experimente pura, em saladas ou sobre diferentes preparos. Uma pequena porção abre muitas combinações.","cta":"Ver semente de abóbora","slug":"pumpkin-seeds","preco":15.90,"apresentacao":"150 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":150,"unidade_venda":"g","incremento":150},
{"id":54,"nome":"Semente de Girassol sem Casca","categoria":"sementes","imagem":"sunflower-seeds.webp","descricao":"Sementes de girassol sem casca para lanches, saladas e receitas.","beneficios":["Crocância","Snack","Versatilidade"],"tipo":"semente","vegana":True,"sem_gluten":True,"experiencia_minima":"iniciante","tags":["semente","girassol","snack","salada"],"disponibilidade":"consultar","destaque":False,"copy":"Uma semente versátil e crocante para beliscar ou acrescentar a saladas, pães e receitas do cotidiano.","cta":"Conhecer esta semente","slug":"sunflower-seeds","preco":8.90,"apresentacao":"200 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":200,"unidade_venda":"g","incremento":200},
{"id":55,"nome":"Uva-Passa Escura","categoria":"frutas-secas","imagem":"raisins.webp","descricao":"Uvas-passas escuras para lanches, granolas, pães e receitas.","beneficios":["Praticidade","Fruta seca","Receitas"],"tipo":"fruta-seca","vegana":True,"sem_gluten":True,"experiencia_minima":"iniciante","tags":["uva passa","fruta seca","lanche","granola"],"disponibilidade":"consultar","destaque":False,"copy":"Do lanche rápido à receita de família: a uva-passa combina praticidade, doçura e muitas possibilidades na despensa.","cta":"Ver uva-passa","slug":"raisins","preco":9.90,"apresentacao":"200 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":200,"unidade_venda":"g","incremento":200},
{"id":56,"nome":"Damasco Seco","categoria":"frutas-secas","imagem":"dried-apricots.webp","descricao":"Damascos secos para lanches, tábuas e combinações com castanhas.","beneficios":["Fruta seca","Snack","Combinações"],"tipo":"fruta-seca","vegana":True,"sem_gluten":True,"experiencia_minima":"iniciante","tags":["damasco","fruta seca","lanche","castanhas"],"disponibilidade":"consultar","destaque":True,"copy":"Macio, levemente adocicado e fácil de levar. Combine com castanhas, monte tábuas ou aproveite como lanche.","cta":"Conhecer o damasco","slug":"dried-apricots","preco":18.90,"apresentacao":"150 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":150,"unidade_venda":"g","incremento":150},
{"id":57,"nome":"Tâmara Seca sem Caroço","categoria":"frutas-secas","imagem":"dried-dates.webp","descricao":"Tâmaras secas sem caroço para lanches e receitas doces.","beneficios":["Fruta seca","Doçura natural","Receitas"],"tipo":"fruta-seca","vegana":True,"sem_gluten":True,"experiencia_minima":"iniciante","tags":["tamara","fruta seca","lanche","receitas"],"disponibilidade":"consultar","destaque":True,"copy":"Uma fruta seca de sabor marcante para lanches, recheios e receitas. A versão sem caroço deixa tudo mais prático.","cta":"Ver tâmaras","slug":"dried-dates","preco":16.90,"apresentacao":"200 g","venda_tipo":"peso","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":200,"unidade_venda":"g","incremento":200},
{"id":58,"nome":"Chips de Batata-Doce","categoria":"snacks","imagem":"sweet-potato-chips.webp","descricao":"Chips crocantes de batata-doce para lanches e momentos de pausa.","beneficios":["Crocância","Pronto para consumir","Snack"],"tipo":"snack","vegana":True,"sem_gluten":True,"experiencia_minima":"iniciante","tags":["chips","batata doce","snack","lanche"],"disponibilidade":"consultar","destaque":True,"copy":"Crocância pronta para acompanhar uma pausa. Um snack fácil de levar e compartilhar, com o sabor da batata-doce.","cta":"Conhecer os chips","slug":"sweet-potato-chips","preco":12.90,"apresentacao":"80 g","venda_tipo":"unidade","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":1,"unidade_venda":"un.","incremento":1},
{"id":59,"nome":"Spirulina em Pó","categoria":"suplementos","imagem":"spirulina-powder.webp","descricao":"Spirulina em pó cadastrada para consulta de composição, apresentação e uso indicado no rótulo.","beneficios":["Formato em pó","Composição consultável","Praticidade"],"tipo":"po","vegana":True,"sem_gluten":True,"experiencia_minima":"intermediario","tags":["spirulina","po","suplemento","vegano"],"disponibilidade":"consultar","destaque":True,"copy":"Spirulina em pó para quem prefere conferir composição e apresentação antes de escolher. Consulte o rótulo e confirme com a equipe como este item é comercializado.","cta":"Ver spirulina","slug":"spirulina-powder","preco":39.90,"apresentacao":"100 g","venda_tipo":"unidade","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":1,"unidade_venda":"un.","incremento":1},
{"id":60,"nome":"Ômega 3","categoria":"suplementos","imagem":"omega-3.webp","descricao":"Suplemento de ômega 3 para consulta de concentração, composição e apresentação.","beneficios":["Composição consultável","Cápsulas","Suplementação"],"tipo":"capsula","vegana":False,"sem_gluten":True,"experiencia_minima":"intermediario","tags":["omega 3","capsulas","suplemento"],"disponibilidade":"consultar","destaque":True,"copy":"Ômega 3 em cápsulas para comparar concentração, quantidade por porção e apresentação. Confira o rótulo e tire dúvidas antes de escolher.","cta":"Conhecer o ômega 3","slug":"omega-3","preco":49.90,"apresentacao":"60 cápsulas","venda_tipo":"unidade","preco_atualizado_em":"2026-08-21","preco_aproximado":False,"preco_fixo":True,"quantidade_base":1,"unidade_venda":"un.","incremento":1}
]
by_id={p["id"]:p for p in products}
for item in new:by_id[item["id"]]=item
data["produtos"]=[by_id[k] for k in sorted(by_id)]
products_path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")

categories_path=ROOT/"data/categories.json";cats=json.loads(categories_path.read_text(encoding="utf-8"));existing={x["id"] for x in cats["categorias"]}
for item in [
 {"id":"farinhas","nome":"Farinhas Funcionais","descricao":"Farinhas para explorar pães, bolos, massas e novas texturas na cozinha.","imagem":"almond-flour.webp"},
 {"id":"frutas-secas","nome":"Frutas Secas","descricao":"Sabores concentrados e práticos para lanches, tábuas, granolas e receitas.","imagem":"dried-apricots.webp"},
 {"id":"snacks","nome":"Snacks Naturais","descricao":"Opções crocantes e práticas para levar, dividir e aproveitar nos intervalos.","imagem":"sweet-potato-chips.webp"}
]:
 if item["id"] not in existing:cats["categorias"].append(item)
categories_path.write_text(json.dumps(cats,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")

for rel in ("README.md","SECURITY.md","data/config.json","data/routes.json","assets/scripts/admin.js","tools/audit-client.py"):
 p=ROOT/rel;p.write_text(p.read_text(encoding="utf-8").replace("3.4.6","3.4.7"),encoding="utf-8")
for p in ROOT.glob("tools/test*.py"):
 if p.name!="test-v347.py":p.write_text(p.read_text(encoding="utf-8").replace("3.4.6","3.4.7"),encoding="utf-8")
for name in ("test-commerce.py","test-v332.py"):
 p=ROOT/"tools"/name;p.write_text(p.read_text(encoding="utf-8").replace("!=47","!=60").replace("==47","==60").replace("47 produtos","60 produtos").replace("47 produtos, encontrados","60 produtos, encontrados"),encoding="utf-8")
v332=ROOT/"tools/test-v332.py";text=v332.read_text(encoding="utf-8").replace("len(p)==60 and len(r['produtos'])==60","len(p)==60 and len(r['produtos'])==47").replace("Pesquisa deve cobrir os 60 produtos","O catálogo deve ter 60 produtos e preservar a pesquisa histórica dos 47 itens originais")
if "Novos produtos devem usar preço fixo" not in text:text=text.replace("ok(all(x.get('preco_atualizado_em') for x in p),'Data de preço ausente')","ok(all(x.get('preco_atualizado_em') for x in p),'Data de preço ausente')\nok(all(x.get('preco_fixo') is True and not x.get('preco_aproximado') for x in p if x['id']>=48),'Novos produtos devem usar preço fixo administrável')")
v332.write_text(text,encoding="utf-8")
sw=ROOT/"service-worker.js";text=sw.read_text(encoding="utf-8").replace("qualimax-v3.4.6","qualimax-v3.4.7");sw.write_text(text,encoding="utf-8")
print("13 produtos e 3 categorias adicionados.")
